[tools]
atlas = "0.36.0"
go = "1.25.0"
golangci-lint = "2.4.0"
opentofu = "1.10.5"
protoc = "32.0"
protoc-gen-go = "1.36.8"
protoc-gen-go-grpc = "1.5.1"
task = "3.44.1"

"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.30.0"
"go:goa.design/goa/v3/cmd/goa" = "3.22.1"